
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: CORRELATED # 消息发送确认 = ack?true:false 服务器端不管有没有接受到消息,都要返回
    publisher-returns: true # 消息发送失败返回 = 队列确认,队列没有收到消息时才会执行消息回退
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  application:
    name: producer-service
server:
  port: 19090

logging:
  level:
    com.zwx.durian.mq.producer.config.MQProducerAckConfig: info